apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-broadcaster
spec:
  replicas: 3
  selector:
    matchLabels:
      app: todo-broadcaster
  template:
    metadata:
      labels:
        app: todo-broadcaster
    spec:
      containers:
        - name: todo-broadcaster
          image: irmindev/todo-broadcaster:2.4
          imagePullPolicy: Always
          env:
            - name: NATS_SERVER
              valueFrom:
                secretKeyRef:
                  name: nats-credentials
                  key: NATS_SERVER
            - name: NATS_SUBJECT
              valueFrom:
                secretKeyRef:
                  name: nats-credentials
                  key: NATS_SUBJECT
            - name: DISCORD_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: nats-credentials
                  key: DISCORD_WEBHOOK
            - name: NATS_QUEUE_GROUP
              value: "todo_group"