namespace: staging

resources:
- ./../../base

patchesStrategicMerge:
- deployment.yaml

images:
- name: PROJECT/IMAGE1
  newName: irmindev/todo-app
  newTag: bbd3215e5294f85376ece4cb1664ccd2a3e877b6
- name: PROJECT/IMAGE2
  newName: irmindev/todo-backend
  newTag: bbd3215e5294f85376ece4cb1664ccd2a3e877b6
- name: PROJECT/IMAGE3
  newName: irmindev/todo-broadcaster
  newTag: bbd3215e5294f85376ece4cb1664ccd2a3e877b6
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
