namespace: staging

resources:
- ./../../base

patchesStrategicMerge:
- deployment.yaml

images:
- name: PROJECT/IMAGE1
  newName: irmindev/todo-app
  newTag: 525086ad038c155e447958f9ee8b17b09e5a954c
- name: PROJECT/IMAGE2
  newName: irmindev/todo-backend
  newTag: 525086ad038c155e447958f9ee8b17b09e5a954c
- name: PROJECT/IMAGE3
  newName: irmindev/todo-broadcaster
  newTag: 525086ad038c155e447958f9ee8b17b09e5a954c
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
