namespace: staging

resources:
- ./../../base

patchesStrategicMerge:
- deployment.yaml

images:
- name: PROJECT/IMAGE1
  newName: irmindev/todo-app
  newTag: e03c0e49e2e5315aa17e01806b8a080225e93237
- name: PROJECT/IMAGE2
  newName: irmindev/todo-backend
  newTag: e03c0e49e2e5315aa17e01806b8a080225e93237
- name: PROJECT/IMAGE3
  newName: irmindev/todo-broadcaster
  newTag: e03c0e49e2e5315aa17e01806b8a080225e93237
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
