namespace: staging

resources:
- ./../../base

patchesStrategicMerge:
- deployment.yaml

images:
- name: PROJECT/IMAGE1
  newName: irmindev/log-output
  newTag: d1cd29f57a8de0a553225670c96380552700baa7
- name: PROJECT/IMAGE2
  newName: irmindev/log-writer
  newTag: d1cd29f57a8de0a553225670c96380552700baa7
- name: PROJECT/IMAGE3
  newName: irmindev/ping-pong
  newTag: d1cd29f57a8de0a553225670c96380552700baa7
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
