namespace: staging

resources:
- ./../../base

patchesStrategicMerge:
- deployment.yaml

images:
- name: PROJECT/IMAGE1
  newName: irmindev/todo-app
  newTag: fdb56a08bc3a278970d8addb30c0d72b225bd891
- name: PROJECT/IMAGE2
  newName: irmindev/todo-backend
  newTag: fdb56a08bc3a278970d8addb30c0d72b225bd891
- name: PROJECT/IMAGE3
  newName: irmindev/todo-broadcaster
  newTag: fdb56a08bc3a278970d8addb30c0d72b225bd891
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
