namespace: staging

resources:
- ./../../base

patchesStrategicMerge:
- deployment.yaml

images:
- name: PROJECT/IMAGE1
  newName: irmindev/log-output
  newTag: 76c35a71b1e76ea326bfce63722a9c43bf714a96
- name: PROJECT/IMAGE2
  newName: irmindev/log-writer
  newTag: 76c35a71b1e76ea326bfce63722a9c43bf714a96
- name: PROJECT/IMAGE3
  newName: irmindev/ping-pong
  newTag: 76c35a71b1e76ea326bfce63722a9c43bf714a96
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
