namespace: staging

resources:
- ./../../base

patchesStrategicMerge:
- deployment.yaml

images:
- name: PROJECT/IMAGE1
  newName: irmindev/todo-app
  newTag: a67f1a8026e7ca5a5854e3942725dab41aa65080
- name: PROJECT/IMAGE2
  newName: irmindev/todo-backend
  newTag: a67f1a8026e7ca5a5854e3942725dab41aa65080
- name: PROJECT/IMAGE3
  newName: irmindev/todo-broadcaster
  newTag: a67f1a8026e7ca5a5854e3942725dab41aa65080
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
