apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
        - name: todo-app
          env:
            - name: BACKEND_URL
              value: "http://todo-backend-svc.production.svc.cluster.local:3456"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
        - name: todo-backend
          env:
            - name: DATABASE_URL
              value: "jdbc:postgresql://postgres-todo-svc.production.svc.cluster.local:5432/todo-app"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-broadcaster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-broadcaster
  template:
    metadata:
      labels:
        app: todo-broadcaster
    spec:
      containers:
        - name: todo-broadcaster
          env:
            - name: DISCORD_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: nats-credentials
                  key: DISCORD_WEBHOOK