namespace: production

resources:
- ./../../base
- cronjob.yaml
- persistentVolumeClaim.yaml
- persistentVolume.yaml

patchesStrategicMerge:
- deployment.yaml

images:
- name: PROJECT/IMAGE1
  newName: irmindev/todo-app
  newTag: 8fd1afcd3941b9b99aa8a7674bfdd1502b7f2697
- name: PROJECT/IMAGE2
  newName: irmindev/todo-backend
  newTag: 8fd1afcd3941b9b99aa8a7674bfdd1502b7f2697
- name: PROJECT/IMAGE3
  newName: irmindev/todo-broadcaster
  newTag: 8fd1afcd3941b9b99aa8a7674bfdd1502b7f2697
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
