namespace: production

resources:
- ./../../base
- cronjob.yaml
- persistentVolumeClaim.yaml
- persistentVolume.yaml

patchesStrategicMerge:
- deployment.yaml

images:
- name: PROJECT/IMAGE1
  newName: irmindev/log-output
  newTag: 068d2b74974a391038362187451cdbe8ee9e708b
- name: PROJECT/IMAGE2
  newName: irmindev/log-writer
  newTag: 068d2b74974a391038362187451cdbe8ee9e708b
- name: PROJECT/IMAGE3
  newName: irmindev/ping-pong
  newTag: 068d2b74974a391038362187451cdbe8ee9e708b
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
