namespace: production

resources:
- ./../../base
- cronjob.yaml
- persistentVolumeClaim.yaml
- persistentVolume.yaml

patchesStrategicMerge:
- deployment.yaml

images:
- name: PROJECT/IMAGE1
  newName: irmindev/todo-app
  newTag: 5a07ab2e759ceda7a0e0985c0d82b99b454b7f67
- name: PROJECT/IMAGE2
  newName: irmindev/todo-backend
  newTag: 5a07ab2e759ceda7a0e0985c0d82b99b454b7f67
- name: PROJECT/IMAGE3
  newName: irmindev/todo-broadcaster
  newTag: 5a07ab2e759ceda7a0e0985c0d82b99b454b7f67
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
