namespace: production

resources:
- ./../../base
- cronjob.yaml
- persistentVolumeClaim.yaml
- persistentVolume.yaml

patchesStrategicMerge:
- deployment.yaml

images:
- name: PROJECT/IMAGE1
  newName: irmindev/log-output
  newTag: ae77b6b4ad2fbc553a6ec98445c046d910245e3c
- name: PROJECT/IMAGE2
  newName: irmindev/log-writer
  newTag: ae77b6b4ad2fbc553a6ec98445c046d910245e3c
- name: PROJECT/IMAGE3
  newName: irmindev/ping-pong
  newTag: ae77b6b4ad2fbc553a6ec98445c046d910245e3c
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
