apiVersion: v1
kind: PersistentVolume
metadata:
  name: backup-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 5Gi
  storageClassName: db-backup #does not need to refer to an existing StorageClass object
  mountOptions:
    - implicit-dirs
    - uid=1001
    - gid=3003
  csi:
    driver: gcsfuse.csi.storage.gke.io
    volumeHandle: irmindev-project-backup-bucket