apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: todo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-app
  strategy:
    canary:
      steps:
      - setWeight: 50
      - pause:
          duration: 30s
      - setWeight: 50
      - pause:
          duration: 30s
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
        - name: todo-app
          image: PROJECT/IMAGE1
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "8080"
            - name: BACKEND_URL
              value: "http://todo-backend-svc.default.svc.cluster.local:3456"
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            limits:
              memory: "600Mi"
      strategy:
        canary:
          steps:
          - setWeight: 50
          - analysis:
              templates:
              - templateName: restart-rate