apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: restart-rate
spec:
  metrics:
  - name: restart-rate
    initialDelay: 2m
    successCondition: result < 0.05
    provider:
      prometheus:
        address: http://kube-prometheus-stack-1722-prometheus.prometheus.svc.cluster.local:9090 # DNS name for my Prometheus, find yours with kubectl describe svc ...
        query: |
          scalar(sum(rate(container_cpu_usage_seconds_total{namespace="default"}[5m])))