apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: todo-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-backend
  strategy:
    canary:
      steps:
      - setWeight: 50
      - pause:
          duration: 30s
      - setWeight: 50
      - pause:
          duration: 30s
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
        - name: todo-backend
          image: PROJECT/IMAGE2
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "8000"
            - name: DATABASE_URL
              value: "jdbc:postgresql://postgres-svc.default.svc.cluster.local:5432/todo-app"
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_USER
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_PASSWORD
          ports:
            - containerPort: 8000
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
      strategy:
        canary:
          steps:
          - setWeight: 50
          - analysis:
              templates:
              - templateName: restart-rate