apiVersion: v1
kind: ServiceAccount
metadata:
  name: db-backup
  annotations:
    iam.gke.io/gcp-service-account: db-backup@dwk-gke-431301.iam.gserviceaccount.com
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-backup
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-backup
  template:
    metadata:
      labels:
        app: db-backup
      annotations:
        gke-gcsfuse/volumes: "true"
    spec:
      serviceAccountName: db-backup
      containers:
        - name: backup
          image: postgres:latest
          env:
            - name: POSTGRES_HOST
              value: "postgres-svc.default.svc.cluster.local"
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_DB
          command: ["sh", "-c", "pg_dump postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@$POSTGRES_HOST/$POSTGRES_DB > /mnt/gcs/backup.sql"]
          volumeMounts:
            - name: gcs-storage
              mountPath: /mnt/gcs
      volumes:
        - name: gcs-storage
          persistentVolumeClaim:
            claimName: backup-pvc
