apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
        - name: todo-app
          image: PROJECT/IMAGE1
          env:
            - name: PORT
              value: "8080"
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 180
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10       
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
        - name: todo-backend
          image: PROJECT/IMAGE2
          env:
            - name: PORT
              value: "8000"
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_USER
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_PASSWORD
            - name: NATS_SERVER
              valueFrom:
                secretKeyRef:
                  name: nats-credentials
                  key: NATS_SERVER
            - name: NATS_SUBJECT
              valueFrom:
                secretKeyRef:
                  name: nats-credentials
                  key: NATS_SUBJECT
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-broadcaster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-broadcaster
  template:
    metadata:
      labels:
        app: todo-broadcaster
    spec:
      containers:
        - name: todo-broadcaster
          image: PROJECT/IMAGE3
          env:
            - name: NATS_SERVER
              valueFrom:
                secretKeyRef:
                  name: nats-credentials
                  key: NATS_SERVER
            - name: NATS_SUBJECT
              valueFrom:
                secretKeyRef:
                  name: nats-credentials
                  key: NATS_SUBJECT
            - name: NATS_QUEUE_GROUP
              value: "todo_group"