apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-todo-stset
spec:
  serviceName: postgres-todo-svc
  replicas: 1
  selector:
    matchLabels:
      app: postgres-todo-app
  template:
    metadata:
      labels:
        app: postgres-todo-app
    spec:
      containers:
      - name: postgres-todo
        image: postgres:15.7-bullseye
        env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: POSTGRES_PASSWORD
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - name: postgres-persistent-storage
          mountPath: /var/lib/postgresql/data
          subPath: postgres
  volumeClaimTemplates:
  - metadata:
      name: postgres-persistent-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: standard-rwo
      volumeMode: Filesystem
      resources:
        requests:
          storage: 1Gi