name: Delete namespace

on: delete

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: kube-cluster
  GKE_ZONE: southamerica-west1-a

jobs:
  delete-namespace:
    if: github.event.ref_type == 'branch'
    name: Delete Namespace
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: google-github-actions/setup-gcloud@v2

      - name: 'Use gcloud CLI'
        run: gcloud info

      - name: 'Get GKE credentials'
        uses: 'google-github-actions/get-gke-credentials@v2'
        with:
          cluster_name: '${{ env.GKE_CLUSTER }}'
          project_id: '${{ env.PROJECT_ID }}'
          location: '${{ env.GKE_ZONE }}'

      - name: Delete namespace
        run: |-
          BRANCH_NAME=${{ github.event.ref }}
          if [ "$BRANCH_NAME" == "main" ]; then
            echo "Skipping deletion of 'default' namespace."
          else
            kubectl delete namespace $BRANCH_NAME || true
          fi