name: Build and publish application

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build-publish:
    name: Build, Push, Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout main branch
        run: |-
          git checkout main


      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # tag image with the GitHub SHA to get a unique tag
      - name: Build and publish todo-app
        run: |-
          docker build --tag "irmindev/todo-app:$GITHUB_SHA" todo-app/
          docker push "irmindev/todo-app:$GITHUB_SHA"

      - name: Build and publish log server
        run: |-
          docker build --tag "irmindev/todo-backend:$GITHUB_SHA" todo-backend/
          docker push "irmindev/todo-backend:$GITHUB_SHA"

      - name: Build and publish ping pong app
        run: |-
          docker build --tag "irmindev/todo-broadcaster:$GITHUB_SHA" todo-broadcaster/
          docker push "irmindev/todo-broadcaster:$GITHUB_SHA"

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2

      # Update kustomization.yaml for staging
      - name: Use right images for staging
        working-directory: overlays/staging
        run: |-
            kustomize edit set image PROJECT/IMAGE1=irmindev/log-output:$GITHUB_SHA
            kustomize edit set image PROJECT/IMAGE2=irmindev/log-writer:$GITHUB_SHA
            kustomize edit set image PROJECT/IMAGE3=irmindev/ping-pong:$GITHUB_SHA

      # Commit changes to kustomization.yaml for staging
      - name: Commit kustomization.yaml for staging to GitHub
        run: |-
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add overlays/staging/kustomization.yaml
          git commit -m "New version released for staging ${{ github.sha }}"
          git push origin main

      # Update kustomization.yaml for production
      - name: Use right images for production
        if: startsWith(github.ref, 'refs/tags/')
        working-directory: overlays/production
        run: |-
            kustomize edit set image PROJECT/IMAGE1=irmindev/log-output:$GITHUB_SHA
            kustomize edit set image PROJECT/IMAGE2=irmindev/log-writer:$GITHUB_SHA
            kustomize edit set image PROJECT/IMAGE3=irmindev/ping-pong:$GITHUB_SHA

      # Commit changes to kustomization.yaml for production
      - name: Commit kustomization.yaml for production to GitHub
        if: startsWith(github.ref, 'refs/tags/')
        run: |-
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add overlays/production/kustomization.yaml
          git commit -m "New version released for production ${{ github.sha }}"
          git pull --rebase origin main
          git push origin main